
#ifndef TIMERS_HPP
#define TIMERS_HPP

#define __AVR_ATmega328P__ // Bunu sil
/*
    1) Hassas Zaman Gecikmeleri (Delay) Oluşturma
        Belirlenen süre dolduğunda işlemciye "zaman doldu" sinyali (Interrupt) gönderilir.
    2) Darbe Genişlik Modülasyonu (PWM) Üretimi
        Timer'lar, dijital sinyallerin "açık" ve "kapalı" kalma sürelerini 
        milisaniyeler seviyesinde kontrol ederek PWM sinyalleri üretir.
    3) Zaman Aralıklı Görevler (Periodic Tasks)
        Sistemin belirli aralıklarla (örneğin her 10 milisaniyede bir) bir sensörden veri okuması veya bir durumu kontrol 
        etmesi gerekiyorsa Timer kullanılır. Bu, ana döngüden (loop veya while) bağımsız olarak tam zamanında gerçekleşen 
        "saat gibi çalışan" görevler sağlar.
    4) Giriş Sinyali Yakalama (Input Capture)
        Dışarıdan gelen bir sinyalin iki yükselen kenarı arasındaki süreyi ölçmek için kullanılır. Bu yöntemle:
            * Bir sinyalin frekansı ölçülebilir.
            * Ultrasonik mesafe sensörlerinden gelen yankı süresi hesaplanarak mesafe ölçülebilir.
            * Bir motorun devir sayısı (RPM) hesaplanabilir.
    5) Olay Sayma (External Event Counter)
        Timer, işlemcinin kendi iç saatini saymak yerine dışarıdaki bir pin üzerinden gelen sinyalleri sayacak şekilde 
        yapılandırılabilir. Örneğin, bir banttan geçen ürünlerin sayısını sayan bir sensör doğrudan Timer girişine 
        bağlanabilir.

*/

#define BITPOS_COM2A COM2A0
#define BITPOS_COM2B COM2B0
#define BITPOS_COM0A COM0A0
#define BITPOS_COM0B COM0B0
#define BITPOS_COM1A COM1A0
#define BITPOS_COM1B COM1B0
#define BITPOS_FOC0A FOC0A
#define BITPOS_FOC0B FOC0B
#define BITPOS_FOC1A FOC1A
#define BITPOS_FOC1B FOC1B
#define BITPOS_FOC2A FOC2A
#define BITPOS_FOC2B FOC2B

#include "registers.hpp"
#include "HAL/sysctrl.hpp"
#include "gpio.hpp"
#include <avr/interrupt.h>
#include "HAL/utils/atomicblock.hpp"

using namespace mcu;


namespace mcu{
namespace Timers{
    class Timer0{
    public:
        enum class Mode         : uint8_t{
            /* */
            Normal                  = 0x00,
            /* */
            PhaseCorrectPWM         = RegBits::Timers::Timer0::TCCR0A_WGM00,
            /* f_out = f_clk/(2*N*(1+OCRx)) 
                * N    :This N variable represents the prescale factor (1, 8, 64, 256, or 1024).
                * f_clk:system clock (cpu) frequency (or external clock frequency on T0 pin (i.e. PD4 pin).)
                * f_out:frequency generated by timer
                * OCRx :Output Compare Register value (8-bit unsigned)
            In clear timer on compare or CTC mode (WGM02:0 = 2), the OCR0A register is used to manipulate the counter resolution. 
            In CTC mode the counter is cleared to zero when the counter value (TCNT0) matches the OCR0A. The OCR0A defines the 
            top value for the counter, hence also its resolution. This mode allows greater control of the compare match output 
            frequency. It also simplifies the operation of counting external events.*/
            ClearTimerOnCompareMatch= RegBits::Timers::Timer0::TCCR0A_WGM01,
            /* */
            FastPWM                 = RegBits::Timers::Timer0::TCCR0A_WGM00|
                                      RegBits::Timers::Timer0::TCCR0A_WGM01,
            PhaseCorrectPWM_WithOCR = RegBits::Timers::Timer0::TCCR0A_WGM00|
                                      RegBits::Timers::Timer0::TCCR0B_WGM02,
            /* FastPWM_WithOCR: 
                This mode gives an PWM output through OC0B pin with variable frequency adjusted by OCR0A value and
            variable duty-cycle adjusted by OCR0B value. OCR0A should be greater than OCR0B otherwise duty-cycle remains 100%.
            OutputModes ClearPinOnCompareMatch and SetPinOnCompareMatch can be used for OutputPinB (OC0B pin), 
            TogglePinOnCompareMatch option has no effect on this pin.
                OutputPinA (OC0A pin) still can be used by selecting TogglePinOnCompareMatch but only with fixed frequency 
            and fixed duty-cycle(50%)*/
            FastPWM_WithOCR         = RegBits::Timers::Timer0::TCCR0A_WGM00|
                                      RegBits::Timers::Timer0::TCCR0A_WGM01|
                                      RegBits::Timers::Timer0::TCCR0B_WGM02,
        };
        enum class Clock        : uint8_t{
            Stopped              = 0x00,                                  //0x00 ...000
            NoPrescaling         = RegBits::Timers::Timer0::TCCR0B_CS00,  //0x01 ...001
            DividedBy8           = RegBits::Timers::Timer0::TCCR0B_CS01,  //0x02 ...010
            DividedBy64          = RegBits::Timers::Timer0::TCCR0B_CS00| 
                                   RegBits::Timers::Timer0::TCCR0B_CS01,  //0x03 ...011
            DividedBy256         = RegBits::Timers::Timer0::TCCR0B_CS02,  //0x04 ...100
            DividedBy1024        = RegBits::Timers::Timer0::TCCR0B_CS00 | 
                                   RegBits::Timers::Timer0::TCCR0B_CS02,  //0x05 ...101
            /* Transitions (high-to-low) on the T0 pin will clock the counter even if the pin is configured as an output. This feature 
            allows software control of the counting.*/
            ExternalOnFallingEdge= RegBits::Timers::Timer0::TCCR0B_CS01 |
                                   RegBits::Timers::Timer0::TCCR0B_CS02,  //0x06 ...110
            /* Transitions (low-to-high) on the T0 pin will clock the counter even if the pin is configured as an output. This feature 
            allows software control of the counting.*/
            ExternalOnRisingEdge = RegBits::Timers::Timer0::TCCR0B_CS00 |
                                   RegBits::Timers::Timer0::TCCR0B_CS01 |
                                   RegBits::Timers::Timer0::TCCR0B_CS02,  //0x07 ...111
        };
        enum class OutputMode   : uint8_t{
            /* Pin is disconnected from output of timer and operates as gpio pin*/
            DisconnectedFromPin     = 0x00,
            /* For FastPWM (WGM2=0)        : Normal port operation, OC0A disconnected.
               For PhaseCorrectMode(WGM2=0): Normal port operation, OC0A disconnected.*/
            TogglePinOnCompareMatch = 0x01,
            ClearPinOnCompareMatch  = 0x02,
            SetPinOnCompareMatch    = 0x03,
        };
        enum class InterruptType: uint8_t{
            OutputCompareMatchA = RegBits::Timers::Timer0::TIMSK0_OCIE0A,
            OutputCompareMatchB = RegBits::Timers::Timer0::TIMSK0_OCIE0B,
            Overflow            = RegBits::Timers::Timer0::TIMSK0_TOIE0,
            All                 = RegBits::Timers::Timer0::TIMSK0_OCIE0A |
                                  RegBits::Timers::Timer0::TIMSK0_OCIE0B |
                                  RegBits::Timers::Timer0::TIMSK0_TOIE0,
        };
    private:
        using Callback = void(*)();                             //callback için fonksiyon tipi
        inline static Callback overflowCallback      = nullptr; //cbOverflow
        inline static Callback compareMatchACallback = nullptr; //cbCompareMatchA
        inline static Callback compareMatchBCallback = nullptr; //cbCompareMatchB
        inline static Clock currentClock;
        template<typename IOPin, uint8_t comBitPos, uint8_t focBitPos> struct OCPin{
                inline void enable(){
                    IOPin::setPinMode(HAL::PinMode::Output);
                }
                inline void setOutputMode(OutputMode out_mode){
                    uint8_t mode = static_cast<uint8_t>(out_mode);
                    uint8_t mask = ~(0x03 << comBitPos);
                    mode <<= comBitPos;
                    mcu::Regs::Timers::Timer0::TimerCounterControlRegA.writeMasked(mode, mask);
                }
                inline void forceOutput(){/* NOT TESTED YET*/
                    if(Regs::Timers::Timer0::TimerCounterControlRegA.readBit(RegBits::Timers::Timer0::TCCR0A_WGM00)) return;
                    mcu::Regs::Timers::Timer0::TimerCounterControlRegB.setBitmask(1 << focBitPos);
                }
            };
        struct TimerInterrupt{
            void enable(InterruptType intType){
                Regs::Timers::Timer0::TimerInterruptMaskReg.setBitmask(static_cast<uint8_t>(intType));
            }
            void disable(InterruptType intType){
                Regs::Timers::Timer0::TimerInterruptMaskReg.clearBitmask(static_cast<uint8_t>(intType));
            }
            void attach(InterruptType intType, Callback callbackFunc){
                switch (intType){
                    case InterruptType::Overflow            :overflowCallback      = callbackFunc; break;
                    case InterruptType::OutputCompareMatchA :compareMatchACallback = callbackFunc; break;
                    case InterruptType::OutputCompareMatchB :compareMatchBCallback = callbackFunc; break;
                    case InterruptType::All:break;
                }
                enable(intType);
            }
            void detach(InterruptType intType){
                switch (intType){
                    case InterruptType::Overflow            :overflowCallback     = nullptr; break;
                    case InterruptType::OutputCompareMatchA :compareMatchACallback= nullptr; break;
                    case InterruptType::OutputCompareMatchB :compareMatchBCallback= nullptr; break;
                    case InterruptType::All                 :overflowCallback     = nullptr;
                                                             compareMatchACallback= nullptr;
                                                             compareMatchBCallback= nullptr; break;
                }
                disable(intType);
            }
            void handler(InterruptType intType){
                switch (intType){
                    case InterruptType::Overflow           : if(overflowCallback)      overflowCallback()     ; break;
                    case InterruptType::OutputCompareMatchA: if(compareMatchACallback) compareMatchACallback(); break;
                    case InterruptType::OutputCompareMatchB: if(compareMatchBCallback) compareMatchBCallback(); break;
                }
            }
        };
    public:
        static OCPin<Gpio::PinOC0A, BITPOS_COM0A, BITPOS_FOC0A> ChannelA;
        static OCPin<Gpio::PinOC0B, BITPOS_COM0B, BITPOS_FOC0B> ChannelB;
        static TimerInterrupt Interrupts;
        static void disable(){
            setClock(Clock::Stopped);
        }
        static void enable(){
            mcu::System::Power::activatePeripheral(Peripheral::Timer0);
            if(currentClock != Clock::Stopped) setClock(currentClock);
        }
        static void setMode(Mode timerMode){
            constexpr uint8_t bitmask_tccra_mode_bits = ~(RegBits::Timers::Timer0::TCCR0A_WGM00|
                                                          RegBits::Timers::Timer0::TCCR0A_WGM01);
            constexpr uint8_t bitmask_tccrb_mode_bits = ~RegBits::Timers::Timer0::TCCR0B_WGM02;
            
            
            Regs::Timers::Timer0::TimerCounterControlRegA.writeMasked(static_cast<uint8_t>(timerMode), bitmask_tccra_mode_bits);
            Regs::Timers::Timer0::TimerCounterControlRegB.writeMasked(static_cast<uint8_t>(timerMode), bitmask_tccrb_mode_bits);

        }
        static void setClock(Clock tmrClock){
            constexpr uint8_t bitmask_tccrb_cs_bits = ~(RegBits::Timers::Timer0::TCCR0B_CS00| 
                                                        RegBits::Timers::Timer0::TCCR0B_CS01| 
                                                        RegBits::Timers::Timer0::TCCR0B_CS02);
            /*Save current tccrb*/
            uint8_t currentTCCRB = Regs::Timers::Timer0::TimerCounterControlRegB.getValue();
            /*Set new clock/prescaler settings*/
            currentTCCRB &= bitmask_tccrb_cs_bits;
            currentTCCRB |= static_cast<uint8_t>(tmrClock);
            /*Update tccrb register*/
            Regs::Timers::Timer0::TimerCounterControlRegB.setValue(currentTCCRB);
            /* Update currentClock*/
            currentClock = tmrClock;
        }
        static void resetCounter(){
            Regs::Timers::Timer0::TimerCounterReg.setValue(0x00);
            Regs::Timers::GeneralTimerCounterControlReg.setBitmask(RegBits::Timers::Common::GTCCR_PSRSYNC);
        }
        inline static void setCounterValue(uint8_t val){
            mcu::Regs::Timers::Timer0::TimerCounterReg = val;
        }
        inline static void setCompareValueA(uint8_t topValue){
            Regs::Timers::Timer0::OutputCompareRegA.setValue(topValue);
        }
        inline static void setCompareValueB(uint8_t topValue){
            Regs::Timers::Timer0::OutputCompareRegB.setValue(topValue);
        }
        static uint8_t getCompareValueA(){
            return Regs::Timers::Timer0::OutputCompareRegA.getValue();
        }
        static uint8_t getCompareValueB(){
            return Regs::Timers::Timer0::OutputCompareRegB.getValue();
        }
        static uint8_t getCounterValue(){
            return Regs::Timers::Timer0::TimerCounterReg.getValue();
        }
        static Clock   getClock(){
            constexpr uint8_t bitmask_tccrb_cs_bits = (RegBits::Timers::Timer0::TCCR0B_CS00| 
                                                       RegBits::Timers::Timer0::TCCR0B_CS01| 
                                                       RegBits::Timers::Timer0::TCCR0B_CS02);
            return (static_cast<Clock>(mcu::Regs::Timers::Timer0::TimerCounterControlRegB.getValue(bitmask_tccrb_cs_bits)));
        }
        static Mode    getMode(){
            constexpr uint8_t bitmask_tccra_mode_bits = (RegBits::Timers::Timer0::TCCR0A_WGM00|
                                                         RegBits::Timers::Timer0::TCCR0A_WGM01);
            constexpr uint8_t bitmask_tccrb_mode_bits = RegBits::Timers::Timer0::TCCR0B_WGM02;
            uint8_t currentMode =(mcu::Regs::Timers::Timer0::TimerCounterControlRegA & bitmask_tccra_mode_bits)|
                                 (mcu::Regs::Timers::Timer0::TimerCounterControlRegB & bitmask_tccrb_mode_bits);
            return (static_cast<Mode>(currentMode));
        }

        static void init(Timer0::Mode   tmrMode = Timer0::Mode::Normal, 
                         Timer0::Clock tmrClock = Timer0::Clock::DividedBy1024){
            /* Disable power reduction for timer0 */
            mcu::Regs::Core::PowerReductionReg.clearBitmask(RegBits::Core::PRR_PRTIM0);
            /* Reset registers: TCCR0A, TCCR0B, TCNT0*/
            mcu::Regs::Timers::Timer0::TimerCounterControlRegA.setValue(0x00);
            mcu::Regs::Timers::Timer0::TimerCounterControlRegB.setValue(0x00);
            mcu::Regs::Timers::Timer0::TimerCounterReg.setValue(0x00);
            /* Select operating mode*/
            setMode(tmrMode);
            /* Select prescaler or external/internal clock*/
            setClock(tmrClock);
        }
        /* BASKA YERE ALINACAK*/
        static uint32_t setFrequency(uint32_t freq){
            if(freq == 0){return 0;}

            uint32_t cpuFrequency = mcu::System::Clock::getCpuFrequency();
            
            Clock timerClockPrescalers[] = {Clock::NoPrescaling,  //1
                                            Clock::DividedBy8,    //8
                                            Clock::DividedBy64,   //64
                                            Clock::DividedBy256,  //256
                                            Clock::DividedBy1024};//1024

            uint16_t timerPrescalers[] = {static_cast<uint16_t>(Clock::NoPrescaling),
                                          static_cast<uint16_t>(Clock::DividedBy8),
                                          static_cast<uint16_t>(Clock::DividedBy64),
                                          static_cast<uint16_t>(Clock::DividedBy256),
                                          static_cast<uint16_t>(Clock::DividedBy1024)};
            Mode currentMode = getMode();
            uint8_t modeDivider = 1;
            if(currentMode == Mode::PhaseCorrectPWM || currentMode == Mode::PhaseCorrectPWM_WithOCR) modeDivider = 2;
            
            // f_out = f_clk/(2*N*(1+OCRx)) --> CTC Mode
            // (f_clk/f_out)/2/N-1 = OCRx, N: 1,8,64...
            for (uint8_t i = 0; i < 5; i++){
                uint32_t ocrValue = cpuFrequency/(2*timerPrescalers[i]*freq);
                if(ocrValue<=255){
                    setCompareValueA(static_cast<uint8_t>(ocrValue));
                    setClock(static_cast<Clock>(timerPrescalers[i]));
                    return cpuFrequency/(2*timerPrescalers[i]*(ocrValue+1));
                }
            }
            return 0;
        }
    };
/*



















*/

    class Timer1{
    public:
        enum class Mode         : uint8_t{
            Normal                           = 0x00,
            PhaseCorrectPWM_8bit             = RegBits::Timers::Timer1::TCCR1A_WGM10,
            PhaseCorrectPWM_9bit             = RegBits::Timers::Timer1::TCCR1A_WGM11,
            PhaseCorrectPWM_10bit            = RegBits::Timers::Timer1::TCCR1A_WGM11| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM10,
            ClearTimerOnCompareMatch_WithOCR = RegBits::Timers::Timer1::TCCR1B_WGM12,
            FastPWM_8bit                     = RegBits::Timers::Timer1::TCCR1B_WGM12| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM10,
            FastPWM_9bit                     = RegBits::Timers::Timer1::TCCR1B_WGM12| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM11,
            FastPWM_10bit                    = RegBits::Timers::Timer1::TCCR1B_WGM12| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM11| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM10,
            PhaseAndFrequencyCorrect_WithICR = RegBits::Timers::Timer1::TCCR1B_WGM13,
            PhaseAndFrequencyCorrect_WithOCR = RegBits::Timers::Timer1::TCCR1B_WGM13| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM10,
            PhaseCorrectPWM_WithICR          = RegBits::Timers::Timer1::TCCR1B_WGM13| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM11,
            PhaseCorrectPWM_WithOCR          = RegBits::Timers::Timer1::TCCR1B_WGM13| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM11| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM10,
            ClearTimerOnCompareMatch_WithICR = RegBits::Timers::Timer1::TCCR1B_WGM13| 
                                               RegBits::Timers::Timer1::TCCR1B_WGM12,
            FastPWM_WithICR                  = RegBits::Timers::Timer1::TCCR1B_WGM13| 
                                               RegBits::Timers::Timer1::TCCR1B_WGM12| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM11,
            FastPWM_WithOCR                  = RegBits::Timers::Timer1::TCCR1B_WGM13| 
                                               RegBits::Timers::Timer1::TCCR1B_WGM12| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM11| 
                                               RegBits::Timers::Timer1::TCCR1A_WGM10,
        };
        enum class OutputMode   : uint8_t{ //  Value   |   OC1A         |   OC1B
            Disconnected         = 0x00,   // ******00 | 00****** (<<6) | **00**** (<<4)
            ToggleOnCompareMatch = 0x01,   // ******01 | 01****** (<<6) | **01**** (<<4)
            ClearOnCompareMatch  = 0x02,   // ******10 | 10****** (<<6) | **10**** (<<4)
            SetOnCompareMatch    = 0x03,   // ******11 | 11****** (<<6) | **11**** (<<4)
        };
        enum class CaptureEdge  : uint8_t{
            Falling =0,
            Rising  =1,
        };
        enum class Clock        : uint8_t{
            Stopped                 = 0x00,
            NoPrescaling            = RegBits::Timers::Timer1::TCCR1B_CS10,
            DividedBy8              = RegBits::Timers::Timer1::TCCR1B_CS11,
            DividedBy64             = RegBits::Timers::Timer1::TCCR1B_CS10|
                                      RegBits::Timers::Timer1::TCCR1B_CS11,
            DividedBy256            = RegBits::Timers::Timer1::TCCR1B_CS12,
            DividedBy1024           = RegBits::Timers::Timer1::TCCR1B_CS10|
                                      RegBits::Timers::Timer1::TCCR1B_CS12,
            ExternalOnFallingEdge   = RegBits::Timers::Timer1::TCCR1B_CS11|
                                      RegBits::Timers::Timer1::TCCR1B_CS12,
            ExternalOnRisingingEdge = RegBits::Timers::Timer1::TCCR1B_CS10|
                                      RegBits::Timers::Timer1::TCCR1B_CS11|
                                      RegBits::Timers::Timer1::TCCR1B_CS12,
        };
        enum class InterruptType: uint8_t{
            InputCapture        = RegBits::Timers::Timer1::TIMSK1_ICIE1,
            OutputCompareMatchB = RegBits::Timers::Timer1::TIMSK1_OCIE1B,
            OutputCompareMatchA = RegBits::Timers::Timer1::TIMSK1_OCIE1A,
            Overflow            = RegBits::Timers::Timer1::TIMSK1_TOIE1,
            All                 = InputCapture | OutputCompareMatchA | OutputCompareMatchB | Overflow,
        };

    private:
        using Callback = void(*)();
        inline static Callback cbOverflowCallback      = nullptr;
        inline static Callback cbCompareMatchACallback = nullptr;
        inline static Callback cbCompareMatchBCallback = nullptr;
        inline static Callback cbInputCaptureCallback  = nullptr;
        static Clock currentClock;
        template<typename IOPin, uint8_t comBitPos, uint8_t focBitPos> struct OCPin{
            inline void enable(){
                IOPin::setPinMode(HAL::PinMode::Output);
            }
            inline void setOutputMode(OutputMode out_mode){
                uint8_t mode = static_cast<uint8_t>(out_mode);
                uint8_t mask = ~(0x03 << comBitPos);
                mode <<= comBitPos;
                mcu::Regs::Timers::Timer1::TimerCounterControlRegA.writeMasked(mode, mask);
            }
            inline void forceOutput(){/* NOT TESTED YET*/
                if(Regs::Timers::Timer1::TimerCounterControlRegA.readBit(RegBits::Timers::Timer1::TCCR1A_WGM10)) return;
                mcu::Regs::Timers::Timer1::TimerCounterControlRegC.setBitmask(1 << focBitPos);
            }
        };
        struct TimerInterrupt{
            void enable(InterruptType intType){
                Regs::Timers::Timer1::TimerInterruptMaskReg.setBitmask(static_cast<uint8_t>(intType));
            }
            void disable(InterruptType intType){
                Regs::Timers::Timer1::TimerInterruptMaskReg.clearBitmask(static_cast<uint8_t>(intType));
            }
            void attach(InterruptType intType, Callback callbackFunc){
                if(InterruptType::All == intType) return;
                switch (intType){
                    case InterruptType::Overflow            :cbOverflowCallback      = callbackFunc; break;
                    case InterruptType::OutputCompareMatchA :cbCompareMatchACallback = callbackFunc; break;
                    case InterruptType::OutputCompareMatchB :cbCompareMatchBCallback = callbackFunc; break;
                    case InterruptType::InputCapture        :cbInputCaptureCallback  = callbackFunc; break;
                    case InterruptType::All:break;
                }
                enable(intType);
            }
            void detach(InterruptType intType){
                switch (intType){
                    case InterruptType::Overflow            :cbOverflowCallback      = nullptr; break;
                    case InterruptType::OutputCompareMatchA :cbCompareMatchACallback = nullptr; break;
                    case InterruptType::OutputCompareMatchB :cbCompareMatchBCallback = nullptr; break;
                    case InterruptType::InputCapture        :cbInputCaptureCallback  = nullptr; break;
                    case InterruptType::All                 :cbOverflowCallback      = nullptr;
                                                             cbCompareMatchACallback = nullptr;
                                                             cbCompareMatchBCallback = nullptr; break;
                }
                disable(intType);
            }
            void handler(InterruptType intType){
                switch (intType){
                    case InterruptType::Overflow           : if(cbOverflowCallback)      cbOverflowCallback()     ; break;
                    case InterruptType::OutputCompareMatchA: if(cbCompareMatchACallback) cbCompareMatchACallback(); break;
                    case InterruptType::OutputCompareMatchB: if(cbCompareMatchBCallback) cbCompareMatchBCallback(); break;
                    case InterruptType::InputCapture       : if(cbInputCaptureCallback)  cbInputCaptureCallback() ; break;
                }
            }
        };

    public:
        static OCPin<Gpio::PinOC1A, BITPOS_COM1A, BITPOS_FOC1A> ChannelA;
        static OCPin<Gpio::PinOC1B, BITPOS_COM1B, BITPOS_FOC1B> ChannelB;
        static Timer1::TimerInterrupt Interrupts;

        static void resetCounter(){
            {AtomicBlock ab;
                /* write high byte (first)*/
                mcu::Regs::Timers::Timer1::TimerCounterReg_HByte = 0x00;
                /* write low byte (last)*/
                mcu::Regs::Timers::Timer1::TimerCounterReg_LByte = 0x00;
            }
        }
        static void setMode(Mode mode){
            /* Bitmask for WGM bits in TCCR1A*/
            constexpr uint8_t bitmask_tccra_wgm_bits = ~(RegBits::Timers::Timer1::TCCR1A_WGM11|
                                                         RegBits::Timers::Timer1::TCCR1A_WGM10);
            /* Bitmask for WGM bits in TCCR1B*/
            constexpr uint8_t bitmask_tccrb_wgm_bits = ~(RegBits::Timers::Timer1::TCCR1B_WGM13|
                                                         RegBits::Timers::Timer1::TCCR1B_WGM12);
            /* Write WGM bits on TCCR1A*/
            Regs::Timers::Timer1::TimerCounterControlRegA.writeMasked(static_cast<uint8_t>(mode), bitmask_tccra_wgm_bits);
            /* Write WGM bits on TCCR1B*/
            Regs::Timers::Timer1::TimerCounterControlRegB.writeMasked(static_cast<uint8_t>(mode), bitmask_tccrb_wgm_bits);
        }
        static void enableNoiseCanceller(){
            mcu::Regs::Timers::Timer1::TimerCounterControlRegB.setBitmask(mcu::RegBits::Timers::Timer1::TCCR1B_ICNC1);
        }
        static void disableNoiseCanceller(){
            mcu::Regs::Timers::Timer1::TimerCounterControlRegB.clearBitmask(mcu::RegBits::Timers::Timer1::TCCR1B_ICNC1);
        }
        static void selectInputCaptureEdge(CaptureEdge edge){
            if(static_cast<bool>(edge)){
                Regs::Timers::Timer1::TimerCounterControlRegB.setBitmask(RegBits::Timers::Timer1::TCCR1B_ICES1);
            }else{
                Regs::Timers::Timer1::TimerCounterControlRegB.clearBitmask(RegBits::Timers::Timer1::TCCR1B_ICES1);
            }
        }
        static void setClock(Timer1::Clock clk){
            constexpr uint8_t bitmask_tccrb_clk_bits = ~(RegBits::Timers::Timer1::TCCR1B_CS10|
                                                         RegBits::Timers::Timer1::TCCR1B_CS11|
                                                         RegBits::Timers::Timer1::TCCR1B_CS12);
            Regs::Timers::Timer1::TimerCounterControlRegB.writeMasked(static_cast<uint8_t>(clk), bitmask_tccrb_clk_bits);
            currentClock = clk;
        }
        static void setCompareValueA(uint16_t compareVal){
            {AtomicBlock ab;
                /* write: high byte (first)*/
                mcu::Regs::Timers::Timer1::OutputCompareRegA_HByte.setValue(compareVal >> 8);
                /* write: low byte (last)*/
                mcu::Regs::Timers::Timer1::OutputCompareRegA_LByte.setValue(compareVal);
            }
        }
        static void setCompareValueB(uint16_t compareVal){
            {AtomicBlock ab;
                /* write high byte first*/
                mcu::Regs::Timers::Timer1::OutputCompareRegB_HByte.setValue(compareVal >> 8);
                /* write low byte*/
                mcu::Regs::Timers::Timer1::OutputCompareRegB_LByte.setValue(compareVal);            
            }
        }
        static void setCounterValue(uint16_t counterVal){
            {AtomicBlock ab;
                /* write high byte (first)*/
                mcu::Regs::Timers::Timer1::TimerCounterReg_HByte = (counterVal >> 8);
                /* write low byte (last)*/
                mcu::Regs::Timers::Timer1::TimerCounterReg_LByte = counterVal;
            }
        }
        static uint16_t getCompareValueA(){
            uint16_t compareVal= 0x0000;
            {AtomicBlock ab;
                /* read low byte first, 0x00*/
                uint8_t lowByte = mcu::Regs::Timers::Timer1::OutputCompareRegA_LByte;
                /* read high byte, 0x--00*/
                compareVal = mcu::Regs::Timers::Timer1::OutputCompareRegA_HByte;
                /* left shift high byte and write low byte, 0x0000*/
                compareVal = (compareVal << 8) | lowByte;
            }
            /* return value*/
            return compareVal;
        }
        static uint16_t getCompareValueB(){
            uint16_t compareVal = 0x0000;
            {AtomicBlock ab;
                /* read low byte first*/
                uint8_t lowByte = mcu::Regs::Timers::Timer1::OutputCompareRegB_LByte;
                /* read high byte*/
                compareVal= mcu::Regs::Timers::Timer1::OutputCompareRegB_HByte;
                /* left shift high byte*/
                compareVal = (compareVal << 8) | lowByte;
            }
            /* return resulting 16bit uint*/
            return compareVal;
        }
        static uint16_t getCounterValue(){
            uint16_t counterVal= 0x0000;
            {AtomicBlock ab;
                uint8_t lowByte = mcu::Regs::Timers::Timer1::TimerCounterReg_LByte;
                counterVal      = mcu::Regs::Timers::Timer1::TimerCounterReg_HByte;
                counterVal      = (counterVal << 8) | lowByte;
            }
            return counterVal;
        }
        static Clock    getClock(){
            constexpr uint8_t bitmask_tccrb_clk_bits = (RegBits::Timers::Timer1::TCCR1B_CS10|
                                                        RegBits::Timers::Timer1::TCCR1B_CS11|
                                                        RegBits::Timers::Timer1::TCCR1B_CS12);
            return static_cast<Clock>(mcu::Regs::Timers::Timer1::TimerCounterControlRegB.getValue(bitmask_tccrb_clk_bits));
        }
        static Mode     getMode(){
            /* Bitmask for WGM bits in TCCR1A*/
            constexpr uint8_t bitmask_tccra_wgm_bits = (RegBits::Timers::Timer1::TCCR1A_WGM11|
                                                        RegBits::Timers::Timer1::TCCR1A_WGM10);
            /* Bitmask for WGM bits in TCCR1B*/
            constexpr uint8_t bitmask_tccrb_wgm_bits = (RegBits::Timers::Timer1::TCCR1B_WGM13|
                                                        RegBits::Timers::Timer1::TCCR1B_WGM12);
            uint8_t currentMode = (mcu::Regs::Timers::Timer1::TimerCounterControlRegA.getValue(bitmask_tccra_wgm_bits))|
                                  (mcu::Regs::Timers::Timer1::TimerCounterControlRegB.getValue(bitmask_tccrb_wgm_bits));
            return (static_cast<Mode>(currentMode));
        }

        static void init(Mode tmrMode, Clock clk = Clock::NoPrescaling){
            /* Disable power reduction for timer1*/
            mcu::System::Power::activatePeripheral(Peripheral::Timer1);
            /* reset regs: tccr1a, tccr1b, tccr1c, tcnt*/
            Regs::Timers::Timer1::TimerCounterControlRegA.setValue(0x00);
            Regs::Timers::Timer1::TimerCounterControlRegB.setValue(0x00);
            Regs::Timers::Timer1::TimerCounterControlRegC.setValue(0x00);
            /* 16-bit timer*/
            setCounterValue(0x0000);

            setMode(tmrMode);
            setClock(clk);
        }

        static void pwmOut(uint32_t pwmFrequency, uint8_t pwmDutyCycle){}
    };
/*
a.Disable the Timer/Counter2 interrupts by clearing OCIE2x and TOIE2.
b.Select clock source by setting AS2 as appropriate.
c.Write new values to TCNT2, OCR2x, and TCCR2x.
d.To switch to asynchronous operation: Wait for TCN2xUB, OCR2xUB, and TCR2xUB.
e.Clear the Timer/Counter2 interrupt flags.
f.Enable interrupts, if needed.




















*/
    class Timer2{
    public:
        enum class Mode         : uint8_t{
            Normal                   = 0x00,
            PhaseCorrectPWM          = RegBits::Timers::Timer2::TCCR2A_WGM20,
            ClearTimerOnCompareMatch = RegBits::Timers::Timer2::TCCR2A_WGM21,
            FastPWM                  = RegBits::Timers::Timer2::TCCR2A_WGM21|
                                       RegBits::Timers::Timer2::TCCR2A_WGM20,
            PhaseCorrectPWM_WithOCR  = RegBits::Timers::Timer2::TCCR2B_WGM22|
                                       RegBits::Timers::Timer2::TCCR2A_WGM20,
            FastPWM_WithOCR          = RegBits::Timers::Timer2::TCCR2B_WGM22|
                                       RegBits::Timers::Timer2::TCCR2A_WGM21|
                                       RegBits::Timers::Timer2::TCCR2A_WGM20,
        };
        enum class OutputMode   : uint8_t{
            DisconnectedFromPin  = 0x00,
            ToggleOnCompareMatch = 0x01,
            ClearOnCompareMatch  = 0x02,
            SetOnCompareMatch    = 0x03,
        };
        enum class Clock        : uint8_t{
            Stopped       = 0x00,
            NoPrescaling  = RegBits::Timers::Timer2::TCCR2B_CS20,
            DividedBy8    = RegBits::Timers::Timer2::TCCR2B_CS21,
            DividedBy32   = RegBits::Timers::Timer2::TCCR2B_CS21|
                            RegBits::Timers::Timer2::TCCR2B_CS20,
            DividedBy64   = RegBits::Timers::Timer2::TCCR2B_CS22,
            DividedBy128  = RegBits::Timers::Timer2::TCCR2B_CS22|
                            RegBits::Timers::Timer2::TCCR2B_CS20,
            DividedBy256  = RegBits::Timers::Timer2::TCCR2B_CS22|
                            RegBits::Timers::Timer2::TCCR2B_CS21,
            DividedBy1024 = RegBits::Timers::Timer2::TCCR2B_CS22|
                            RegBits::Timers::Timer2::TCCR2B_CS21|
                            RegBits::Timers::Timer2::TCCR2B_CS20,
        };
        enum class ClockSource  : uint8_t{
            /* Clock signal (square wave 50% duty cycle) is applied on Tosc1 pin. Tosc2 pin is freed.*/
            ExternalClock   = RegBits::Timers::Timer2::ASSR_EXCLK|
                              RegBits::Timers::Timer2::ASSR_AS2,
            /* Clock signal for Timer2 is generated by using crystal connected to Tosc1 and Tosc2 pins.*/
            ExternalCrystal = RegBits::Timers::Timer2::ASSR_AS2,
            /* Timer2 uses internal clock (main clock/system clock)*/
            SystemClock     = 0x00,
        };
        enum class InterruptType: uint8_t{
            OutputCompareMatchB = RegBits::Timers::Timer2::TIMSK2_OCIE2B,
            OutputCompareMatchA = RegBits::Timers::Timer2::TIMSK2_OCIE2A,
            Overflow            = RegBits::Timers::Timer2::TIMSK2_TOIE2,
            All                 = OutputCompareMatchA | OutputCompareMatchB | Overflow,
        };
    private:
        using Callback = void(*)();
        inline static Callback cbOverflowCallback      = nullptr; //cbOverflow
        inline static Callback cbCompareMatchACallback = nullptr; //cbCompareMatchA
        inline static Callback cbCompareMatchBCallback = nullptr; //cbCompareMatchB
        inline static Clock currentClock;
        static ClockSource getClockSource(){
            constexpr static uint8_t bitmask_assr_clksrc_bits =(RegBits::Timers::Timer2::ASSR_EXCLK|
                                                                RegBits::Timers::Timer2::ASSR_AS2);
            return static_cast<ClockSource>(Regs::Timers::Timer2::AsynchronousStatusReg & bitmask_assr_clksrc_bits);
        }
        template<typename IOPin, uint8_t comBitPos, uint8_t focBitPos> struct OCPin{
                inline void enable(){
                    IOPin::setPinMode(HAL::PinMode::Output);
                }
                inline void setOutputMode(OutputMode out_mode){
                    uint8_t mode = static_cast<uint8_t>(out_mode);
                    uint8_t mask = ~(0x03 << comBitPos);
                    mode <<= comBitPos;
                    mcu::Regs::Timers::Timer2::TimerCounterControlRegA.writeMasked(mode, mask);
                }
                inline void forceOutput(){/* NOT TESTED YET*/
                    if(Regs::Timers::Timer2::TimerCounterControlRegA.readBit(RegBits::Timers::Timer2::TCCR2A_WGM20)) return;
                    mcu::Regs::Timers::Timer2::TimerCounterControlRegB.setBitmask(1 << focBitPos);
                }
            };
        struct TimerInterrupt{
            void enable(InterruptType intType){
                Regs::Timers::Timer2::TimerInterruptMaskReg.setBitmask(static_cast<uint8_t>(intType));
            }
            void disable(InterruptType intType){
                Regs::Timers::Timer2::TimerInterruptMaskReg.clearBitmask(static_cast<uint8_t>(intType));
            }
            void attach(InterruptType intType, Callback callbackFunc){
                if(intType == InterruptType::All) return;
                switch (intType){
                    case InterruptType::Overflow            :cbOverflowCallback      = callbackFunc; break;
                    case InterruptType::OutputCompareMatchA :cbCompareMatchACallback = callbackFunc; break;
                    case InterruptType::OutputCompareMatchB :cbCompareMatchBCallback = callbackFunc; break;
                    case InterruptType::All:break;
                }
                enable(intType);
            }
            void detach(InterruptType intType){
                switch (intType){
                    case InterruptType::Overflow            :cbOverflowCallback     = nullptr; break;
                    case InterruptType::OutputCompareMatchA :cbCompareMatchACallback= nullptr; break;
                    case InterruptType::OutputCompareMatchB :cbCompareMatchBCallback= nullptr; break;
                    case InterruptType::All                 :cbOverflowCallback     = nullptr;
                                                             cbCompareMatchACallback= nullptr;
                                                             cbCompareMatchBCallback= nullptr; break;
                }
                disable(intType);
            }
            void handler(InterruptType intType){
                switch (intType){
                    case InterruptType::Overflow           : if(cbOverflowCallback)      cbOverflowCallback()     ; break;
                    case InterruptType::OutputCompareMatchA: if(cbCompareMatchACallback) cbCompareMatchACallback(); break;
                    case InterruptType::OutputCompareMatchB: if(cbCompareMatchBCallback) cbCompareMatchBCallback(); break;
                }
            }
        };
    public:
        static OCPin<Gpio::PinOC2A, BITPOS_COM0A, BITPOS_FOC0A> ChannelA;
        static OCPin<Gpio::PinOC2B, BITPOS_COM0B, BITPOS_FOC0B> ChannelB;
        static TimerInterrupt Interrupts;
        inline static void synch(){
            mcu::Regs::Timers::GeneralTimerCounterControlReg.setBitmask(mcu::RegBits::Timers::Common::GTCCR_PSRASY);
        }
        static void clearCounter(){
            mcu::Regs::Timers::Timer2::TimerCounterReg = 0x00;
            if(ClockSource::SystemClock != getClockSource()){
                while(Regs::Timers::Timer2::AsynchronousStatusReg.readBit(RegBits::Timers::Timer2::ASSR_TCN2UB));
            }
        }
        static void resetCounter(){
            clearCounter();
            synch();
        }
        static void disable(){
            setClock(Clock::Stopped);
        }
        static void enable(){
            mcu::System::Power::activatePeripheral(Peripheral::Timer2);
            if(currentClock != Clock::Stopped) setClock(currentClock);
        }
        static void setClock(Clock clk){
            constexpr uint8_t bitmask_tccrb_clk_bits = ~(RegBits::Timers::Timer2::TCCR2B_CS22|
                                                         RegBits::Timers::Timer2::TCCR2B_CS21|
                                                         RegBits::Timers::Timer2::TCCR2B_CS20);
            mcu::Regs::Timers::Timer2::TimerCounterControlRegB.writeMasked(static_cast<uint8_t>(clk), bitmask_tccrb_clk_bits);
            if(ClockSource::SystemClock != getClockSource()){
                while(Regs::Timers::Timer2::AsynchronousStatusReg.readBit(RegBits::Timers::Timer2::ASSR_TCR2BUB));
            }
            currentClock = clk;
        };
        static void selectClockSource(ClockSource clkSrc){
            constexpr static uint8_t bitmask_assr_clksrc_bits =~(RegBits::Timers::Timer2::ASSR_EXCLK|
                                                                RegBits::Timers::Timer2::ASSR_AS2);
            mcu::Regs::Timers::Timer2::AsynchronousStatusReg.writeMasked(static_cast<uint8_t>(clkSrc), bitmask_assr_clksrc_bits);
            
        };
        static void setMode(Timer2::Mode timerMode){
            /* TCCR2A    :|-|-|-|-|-|-|WGM21|WGM20|*/
            constexpr uint8_t bitmask_tccra_mode_bits = ~(RegBits::Timers::Timer2::TCCR2A_WGM20|
                                                          RegBits::Timers::Timer2::TCCR2A_WGM21);
            /* TCCR2B    :|-|-|-|-|WGM22|-|-|-|*/
            constexpr uint8_t bitmask_tccrb_mode_bits = ~(RegBits::Timers::Timer2::TCCR2B_WGM22);
            /* TCCR2(A+B):|-|-|-|-|WGM22|-|WGM21|WGM20|*/
            Regs::Timers::Timer2::TimerCounterControlRegA.writeMasked(static_cast<uint8_t>(timerMode), bitmask_tccra_mode_bits);
            Regs::Timers::Timer2::TimerCounterControlRegB.writeMasked(static_cast<uint8_t>(timerMode), bitmask_tccrb_mode_bits);
            
            if(ClockSource::SystemClock != getClockSource()){
                while(Regs::Timers::Timer2::AsynchronousStatusReg.readBit(RegBits::Timers::Timer2::ASSR_TCR2BUB));
            }
        }
        static Mode getMode(){
            /* TCCR2A    :|-|-|-|-|-|-|WGM21|WGM20|*/
            constexpr uint8_t bitmask_tccra_mode_bits = (RegBits::Timers::Timer2::TCCR2A_WGM20|
                                                         RegBits::Timers::Timer2::TCCR2A_WGM21);
            /* TCCR2B    :|-|-|-|-|WGM22|-|-|-|*/
            constexpr uint8_t bitmask_tccrb_mode_bits = (RegBits::Timers::Timer2::TCCR2B_WGM22);
            uint8_t mode = Regs::Timers::Timer2::TimerCounterControlRegA.getValue(bitmask_tccra_mode_bits)|
                           Regs::Timers::Timer2::TimerCounterControlRegB.getValue(bitmask_tccrb_mode_bits);
            return (static_cast<Mode>(mode));
        }
        inline static void setCompareValueA(uint8_t compareVal){
            mcu::Regs::Timers::Timer2::OutputCompareRegA.setValue(compareVal);
            if(ClockSource::SystemClock != getClockSource()){
                while(Regs::Timers::Timer2::AsynchronousStatusReg.readBit(RegBits::Timers::Timer2::ASSR_OCR2AUB));
            }
        };
        inline static void setCompareValueB(uint8_t compareVal){
            mcu::Regs::Timers::Timer2::OutputCompareRegB.setValue(compareVal);
            if (ClockSource::SystemClock != getClockSource()){
                while(Regs::Timers::Timer2::AsynchronousStatusReg.readBit(RegBits::Timers::Timer2::ASSR_OCR2BUB));
            }
        };
        inline static void setCounterValue(uint8_t counterVal){
            mcu::Regs::Timers::Timer2::TimerCounterReg.setValue(counterVal);
            if(ClockSource::SystemClock != getClockSource()){
                while(Regs::Timers::Timer2::AsynchronousStatusReg.readBit(RegBits::Timers::Timer2::ASSR_TCN2UB));
            }
        };
        static uint8_t getCompareValueA(){
            return mcu::Regs::Timers::Timer2::OutputCompareRegA;
        };
        static uint8_t getCompareValueB(){
            return mcu::Regs::Timers::Timer2::OutputCompareRegB;
        };
        static uint8_t getCounterValue(){
            return mcu::Regs::Timers::Timer2::TimerCounterReg;
        };
        static void syncTimer(){

        }
        static void init(Mode mode, 
                         Clock clk = Clock::NoPrescaling, 
                         ClockSource clkSource = ClockSource::SystemClock){
            /* Disable power reduction to timer2*/
            mcu::System::Power::activatePeripheral(Peripheral::Timer2);
            /* Reset TCCR2A, TCCR2B, TCNT2*/
            Regs::Timers::Timer2::TimerCounterControlRegA.setValue(0x00);
            Regs::Timers::Timer2::TimerCounterControlRegB.setValue(0x00);
            Regs::Timers::Timer2::TimerCounterReg.setValue(0x00);
            /* Set timer mode*/
            setMode(mode);
            /* Set clock source*/
            selectClockSource(clkSource);
            /* Set clock prescaler*/
            setClock(clk);
        }
    };

} // namespace Timers    
} // namespace mcu


/* Timer0 Overflow Interrupt*/
ISR(TIMER0_OVF_vect){mcu::Timers::Timer0::Interrupts.handler(mcu::Timers::Timer0::InterruptType::Overflow);}
/* Output compare match A interrupt*/
ISR(TIMER0_COMPA_vect){mcu::Timers::Timer0::Interrupts.handler(mcu::Timers::Timer0::InterruptType::OutputCompareMatchA);}
/* Output compare match B interrupt*/
ISR(TIMER0_COMPB_vect){mcu::Timers::Timer0::Interrupts.handler(mcu::Timers::Timer0::InterruptType::OutputCompareMatchB);}

/* Timer1 overflow interrupt*/
ISR(TIMER1_OVF_vect){mcu::Timers::Timer1::Interrupts.handler(mcu::Timers::Timer1::InterruptType::Overflow);}
/* Timer1 output compare match A interrupt*/
ISR(TIMER1_COMPA_vect){mcu::Timers::Timer1::Interrupts.handler(mcu::Timers::Timer1::InterruptType::OutputCompareMatchA);}
/* Timer1 output compare match B interrupt*/
ISR(TIMER1_COMPB_vect){mcu::Timers::Timer1::Interrupts.handler(mcu::Timers::Timer1::InterruptType::OutputCompareMatchB);}
/* Timer1 capture event interrupt*/
ISR(TIMER1_CAPT_vect){mcu::Timers::Timer1::Interrupts.handler(mcu::Timers::Timer1::InterruptType::InputCapture);}

/* Timer2 */
ISR(TIMER2_OVF_vect){mcu::Timers::Timer2::Interrupts.handler(mcu::Timers::Timer2::InterruptType::Overflow);}
/* Timer2 */
ISR(TIMER2_COMPA_vect){mcu::Timers::Timer2::Interrupts.handler(mcu::Timers::Timer2::InterruptType::OutputCompareMatchA);}
/* Timer2 */
ISR(TIMER2_COMPB_vect){mcu::Timers::Timer2::Interrupts.handler(mcu::Timers::Timer2::InterruptType::OutputCompareMatchB);}

#endif //TIMERS_HPP




void count(){
    static uint32_t cycle = 0;
    cycle++;
}

void foof(){
    using T2 = mcu::Timers::Timer2;     
    T2::init(T2::Mode::Normal,
             T2::Clock::NoPrescaling,
             T2::ClockSource::ExternalClock);
    T2::Interrupts.attach(T2::InterruptType::Overflow, count);
    T2::selectClockSource(T2::ClockSource::SystemClock);
    mcu::Gpio::PinTOSC2::setPinMode(HAL::PinMode::Output);
    mcu::Gpio::PinTOSC2::setHigh();
    
}